api:
  embedding_url: https://api.siliconflow.cn/v1/embeddings
  model_name: netease-youdao/bce-embedding-base_v1
  siliconflow_api_key: sk-cwqgdyzqbrgkzkppxtcwfnwphcpzyrbvzndnkgmzhxhqivew
  timeout: 20
logging:
  level: INFO
  log_file: logs/vocabmaster.log
  save_to_file: true
semantic:
  enable_dynamic_threshold: true
  enable_fallback_matching: true
  enable_keyword_matching: true
  min_word_length: 2
  similarity_threshold: 0.55
test:
  default_question_count: 10
  max_question_count: 100
  verbose_logging: true
ui:
  font_family: Times New Roman
  font_size: 16
  window_height: 600
  window_width: 800
